# Generated by Django 5.0.4 on 2024-05-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Especialidad', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('Dni', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Fecha_nacimiento', models.DateField(max_length=50)),
                ('Genero', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('hora', models.TimeField()),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Centro.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Centro.paciente')),
            ],
        ),
    ]
