# Generated by Django 5.0.4 on 2024-05-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Fecha_nacimiento',
            field=models.CharField(max_length=50),
        ),
    ]
