# Generated by Django 5.0.4 on 2024-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centro', '0002_alter_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='id_medico',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='Especialidad',
        ),
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(choices=[('Cardiología', 'Cardiología'), ('Dermatología', 'Dermatología'), ('Neurología', 'Neurología'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología')], max_length=25),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Cardiología', 'Cardiología'), ('Dermatología', 'Dermatología'), ('Neurología', 'Neurología'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología')], default='Cardiología', max_length=25),
        ),
    ]
