# Generated by Django 5.0.4 on 2024-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centro', '0003_rename_id_medico_cita_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Cardiología', 'Cardiología'), ('Dermatología', 'Dermatología'), ('Neurología', 'Neurología'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología')], max_length=25),
        ),
    ]
