# Generated by Django 5.0.4 on 2024-07-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centro', '0004_alter_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Ubigeo',
            field=models.IntegerField(default=21309),
            preserve_default=False,
        ),
    ]
