# Generated by Django 5.0.4 on 2024-07-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Centro', '0005_paciente_ubigeo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Ubigeo',
            new_name='Codigo_postal',
        ),
    ]
